language: go
sudo: required
go:
  - 1.x
  - tip
os:
  - linux
before_install:
  - go get -d ./...
script:
  - go build -tags=gofuzz ./...
  - go vet ./...
  - go test -v -tags=integration ./...
  - .travis/tests.sh
